- lua/trouble/view.lua
Currently trouble preview centers the screen on line in question. If that line is inside fold, it is not really helpful as nothing is actually shown.
This PR adds "opening enough folds" with `zv` alongside with centering the screen. Another cool thing would be to restore folds to previous state after finishing preview, but this is not really a trivial task.
> Open "enough folds" in preview

- README.md
- doc/lsp-trouble.txt
- lua/trouble/config.lua
- lua/trouble/folds.lua
This PR implements a `default_fold` option: a state at which file's trouble list appears when newly created.
Implementation seems a bit hacky. It relies on an implicit assumption that file's diagnostics is newly created if there is no record of it inside `trouble.folds.folded`. Please, feel free to rewrite it if there is a better way.
> Implement 'default_fold' option

- lua/trouble/view.lua
Set keymaps with `nowait` option, this allow users to set single key actions, ex. use `=` to toggle "folds" like the default fugitive mapping
> fix: Add nowait option to keymap

- lua/trouble/view.lua
When trying to open telescope from the trouble window it would fail
because `self.parent_state` was `nil` and it was trying to get `buf` on
it.
> Fix for indexing nil parent_state

- lua/trouble/providers/telescope.lua
Commit 79513ed broke the telescope provider because of the handling of
options changed.
> Fix for telescope provider

- lua/trouble/providers/telescope.lua
Adds support for Telescope's multiselect mode and smart select mode.
- Multiselect: Only the selected entries are shown in Trouble.
- Smart: If you have selected some entries, only those entries will be shown in Trouble. Otherwise all entries will be shown.
> feat(telescope provider): (Smart) multiselect

- README.md
- lua/trouble/providers/init.lua
- lua/trouble/providers/lsp.lua
Same as #20 but for `textDocument/implementation` instead
> Lsp implementation

- lua/trouble/providers/lsp.lua
Small fix to avoid issues with servers that respond with `uri` rather than `targetUri`
> fix(lsp): avoid overwriting uri of result

- README.md
- lua/trouble/providers/init.lua
- lua/trouble/providers/lsp.lua
This PR adds support for the textDocument/typeDefinition feature, allowing you to jump to the definition of the type of a given value
> Add support for lsp type definitions

- plugin/trouble.vim
Use the new DiagnosticChanged event on neovim 0.6.
closes: #122
> fix: use new DiagnosticChanged event

- README.md
Configuration fails for an icon-less setup with the given example if `icons = false` is not explicitly set.
> Set `icons = false` in icon-less setup example

- lua/trouble/view.lua
Theme plugins can apply darkened highlights on it for example.
Should solve this issue: https://github.com/folke/tokyonight.nvim/issues/126
> Set the filetype lastly so autocmd's can override options from it

- README.md
We can use the new, easier [syntax for keybindings](https://github.com/neovim/neovim/pull/16591). Also change the bindings to use `TroubleToggle` instead of `Trouble` so it matches the other keybinding examples
> Update lua example keybindings

- lua/trouble/config.lua
- lua/trouble/providers/init.lua
For example, to sort entries by line number, use:
```lua
require("trouble").setup({
sort_keys = {
"filename",
"lnum",
"col",
"severity",
}
})
```
The defaults remain the same.
Fixes: https://github.com/folke/trouble.nvim/issues/65
> Make sorting keys configurable

- README.md
> docs: README: fixed typo

- lua/trouble/util.lua
This PR fixes an error where sometimes, jump_to_item would crash in case the window-id was `nil` for some reason.
By just defaulting to 0 in that case, we can avoid that error trivially.
This error occurred when auto_jump was used.
The fix does not introduce any other breaking changes or behavior changes.
> Default to current window in jump_to_item

- README.md
- lua/trouble/init.lua
- lua/trouble/view.lua
This allows settings mappings like the quickfix `]Q` and `[Q`
> feat: Api to go to first and last items

- lua/trouble/view.lua
Filetype is set before width or height, which breaks changing the window position inside autocommands from outside of the plugin. Move it after setting the width/height.
> fix: filetype set too early

- lua/trouble/view.lua
I noticed that when I had padding set to `false` I was being dropped on the wrong line. This fix makes sure that we only move down two lines if padding is set to `true`.
> fix: ensure first line is selected when padding is false

- lua/trouble/view.lua
I believe this should fix #240, #59, and #209, and #189. It simply focuses `self.parent` before calling `nvim_win_close()` in the `View:close()` function. As far as I can tell, this function is only called when the Trouble window/list is closed (with `q` or `:TroubleToggle` or `:TroubleClose`).
I think this should be less likely to cause issues than the change in https://github.com/folke/trouble.nvim/pull/72 that was reverted. That change modified `View:close_preview()`, which is called every time the [`BufLeave` autocmd](https://github.com/folke/trouble.nvim/blob/main/lua/trouble/view.lua#L181) is triggered, which (in addition to when closing the Trouble window) happens every time you select a diagnostic item in the Trouble window with `Return`.
> Focus parent before closing

- lua/trouble/view.lua
`:Trouble lsp_definitions` can sometimes leak window options to new windows.
> fix: set window options locally

- lua/trouble/util.lua
```lua
local fd = assert(uv.fs_open(filename, "r", 438))
```
the `filename` might not be an valid file path, for example, the jdtls could return something like this `jdt://contents/commons-collections4-4.4.jar/org.apache.commons.collections4.list/AbstractLinkedList.class?=b`
it causes an error
```
stack traceback:
[C]: in function 'assert'
....local/share/nvim/lazy/trouble.nvim/lua/trouble/util.lua:150: in function 'process_item'
....local/share/nvim/lazy/trouble.nvim/lua/trouble/util.lua:193: in function 'locations_to_items'
...are/nvim/lazy/trouble.nvim/lua/trouble/providers/lsp.lua:44: in function 'handler'
...are/nvim/lazy/trouble.nvim/lua/trouble/providers/lsp.lua:9: in function 'handler'
...w/Cellar/neovim/0.9.0/share/nvim/runtime/lua/vim/lsp.lua:1394: in function '' …
```
> read item contents by `bufnr` instead of reading file by path

- lua/trouble/view.lua
When exiting neovim with only one window open (besides trouble), there's no parent window to set active. This verifies that the parent window is valid before setting it active.
With this in place, neovim exits cleanly when trouble is the last window open. If there is another window, that window becomes active and neovim does not exit.
Fixes #284
> Check parent window is valid before setting active

- README.md
- lua/trouble/config.lua
- lua/trouble/view.lua
Add new cycle_results option (default: true, the current behavior), to control whether to cycle the results list when reaching the beginning or end of the list.
I find myself regularly disoriented about where I am in a list of diagnostics when I cycle back to the beginning without realizing it.  I always prefer to stop when I reach the end of the list so that it's obvious that I'm at the end (like setting `scroll_strategy = limit` in telescope).  Going back to the beginning is simple enough with normal vim movements.
> feat: add option to control cycling of result list

- lua/trouble/providers/diagnostic.lua
- lua/trouble/providers/init.lua
- lua/trouble/renderer.lua
use the padded line as a status bar, so we can display some messages from the provider
for example, in the `diagnostics` mode,  we can show it's current severity filter in it.
#301
> feat: rendering messages from provider

- README.md
This updates the examples to use the new lua mapping functions in neovim 0.7.
`remap = false` is the default, so no need to specify `noremap = true`. `silent` has no effect here.
> Update lua examples to use new mapping functions

- README.md
- lua/trouble/config.lua
- lua/trouble/init.lua
- lua/trouble/util.lua
- lua/trouble/view.lua
LSP diagnostics can have [`codeDescription`s](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeDescription), which contain a link with more information about the error. This PR adds a new action to open these from Trouble :)
> Use code descriptions for opening URIs with extra information

- README.md
- doc/trouble.nvim.txt
- lua/trouble/config.lua
- lua/trouble/providers/lsp.lua
Currently, when `references`, `implementations`, or `definitions`  is called, `includeDeclaration` is set to `true` by default.
This is cumbersome when you are on a definition and call `lsp_references` when there is only 1 reference. Instead of instantly jumping to said reference, a Trouble window appears including that sole reference as well as the your current position.  
I'm sure there may be other scenarios, but this is the one I most frequently run into. 
This PR adds a `include_declaration` list in the config. Only modes that are in this list will `include_declaration` set to `true`. All current modes using it have been set as a default so it doesn't break anyones workflow.
> Create Configuration for IncludeDeclaration

- README.md
The lua keybinds below were like this:
```
vim.keymap.set("n", "<leader>xl", function() require("trouble").open("quickfix") end)
vim.keymap.set("n", "<leader>xq", function() require("trouble").open("loclist") end)
```
As it might not be noticeable the `<leader>xl` keybinding was opening the `quickfix` and the `<leader>xq` keybinding was opening the `loclist`.
So I thought about changing the order just to be more straight forward to new users and to be in sync with the vim keybindings above the lua ones and the result was:
```
vim.keymap.set("n", "<leader>xq", function() require("trouble").open("quickfix") end)
vim.keymap.set("n", "<leader>xl", function() require("trouble").open("loclist") end)
```
> Fix lua keybindings in README

- lua/trouble/providers/diagnostic.lua
Fixes previous breaking change #304 that prevented nvim severity tables from working, such as:
```
require("trouble").setup({
severity = { min = vim.diagnostic.severity.INFO },
})
```
Optimal fix might be a less naive way of filtering severity, but I'd leave that for somebody that cares about this feature.
> fix: only filter msg if sev is hardcoded

- lua/trouble/view.lua
Continuation of 46b60e9.
Skip preview for non-existing buffer (`bufnr == 0`).
The vim docs say:
```
getqflist()
Quickfix list entries with a non-existing buffer
number are returned with "bufnr" set to zero (Note: some
functions accept buffer number zero for the alternate buffer,
you may need to explicitly check for zero).
```
This causes trouble for the "`Trouble`" file section:
To fix, we simply do:
```lua
function View:_preview()
...
if item.bufnr == 0 then
return
end
util.debug("preview")
...
end
```
> fix(preview): skip non-existing. Fixes #87. Fixes #188. Fixes #336.

- README.md
The `Trouble` command is only exposed if we call `opts` or `config` when installing the plugin, it should be documented.
Alternatively, since the default options works well, it would be great to make the plugin config-less by exposing [something like this](https://github.com/shortcuts/no-neck-pain.nvim/blob/main/plugin/no-neck-pain.lua) (_not trying to promo the repository, just using it as an example, feel free to edit the PR body if you feel like it_)
> chore(README): mention `opts` in install

- docs/examples.md
- lua/trouble/async.lua
- lua/trouble/sources/diagnostics.lua
- lua/trouble/util.lua
- tests/init.lua
Resolves #416 
This change makes sure that existing uses of libuv support using both the old and new name in Neovim (vim.loop for Neovim < 0.10 and vim.uv for Neovim >= 0.10)
> Support vim.loop for Neovim < 0.10 and vim.uv for 0.10 and greater

- lua/trouble/view/init.lua
Follow-up of https://github.com/folke/trouble.nvim/pull/418,
https://github.com/folke/trouble.nvim/issues/416
Without this fix the plugin doesn't work at all on nvim 0.9.5
> fix: use vim.loop for nvim 0.9 in view/init.lua

- lua/trouble/util.lua
Just fixes one vim.uv usage you have missed.
Thank you =)
> fix(utils): use `vim.loop or vim.uv` declared in the beginning of a file

- lua/trouble/sources/telescope.lua
When sending telescope result to trouble, if there is no `col` field in the item (e.g. `telescope builtin.current_buffer_fuzzy_find`), the operation will fail with the following error:
```
E5108: Error executing lua: ...m/plugins/trouble.nvim/lua/trouble/sources/telescope.lua:55: bad argument #1 to 'sub' (number expected, got nil)
stack traceback:
[C]: in function 'sub'
...m/plugins/trouble.nvim/lua/trouble/sources/telescope.lua:55: in function 'item'
...m/plugins/trouble.nvim/lua/trouble/sources/telescope.lua:99: in function 'add'
...m/plugins/trouble.nvim/lua/trouble/sources/telescope.lua:120: in function 'key_func'
...e/nvim/plugins/telescope.nvim/lua/telescope/mappings.lua:293: in function <...e/nvim/plugins/telescope.nvim/lua/telescope/mappings.lua:292>
```
This PR will make trouble …
> fix: use (lnum, 0) for telescope item without col

- lua/trouble/format.lua
This PR fixes the error-spamming that happens on opening Trouble when `vim.diagnostic.config().signs(0,0)` somewhy returns boolean (but Trouble expects it to be a table)
> fix(format): for "attempt to index local 'signs' (a boolean value)" errors in nvim-0.10.1+

- README.md
- doc/trouble.nvim.txt
Small mistake in the doc, maybe the API changed as some point and this wasn't updated. Stumbled over this as the version in the README didn't work for me.
> fix(docs): readme/doc example for `Trouble symbols`

- README.md
- lua/trouble/config/actions.lua
Adds `jump_split_close` and `jump_vsplit_close` actions.
> feat(config): add `close` counterparts to jump split actions

- lua/trouble/view/treesitter.lua
The get_parser and TSHighlight:new both parse the buffer which takes a lot of time since there are many error nodes, so set regions early to prevent this.
Both get_parser and TSHighlighter.new calls this [parse](https://github.com/neovim/neovim/blob/cd8e15e3373dc9544d582640f043d3dee83a953d/runtime/lua/vim/treesitter/languagetree.lua#L424), which calls [parse_regions](https://github.com/neovim/neovim/blob/cd8e15e3373dc9544d582640f043d3dee83a953d/runtime/lua/vim/treesitter/languagetree.lua#L340), and [this](https://github.com/neovim/neovim/blob/cd8e15e3373dc9544d582640f043d3dee83a953d/runtime/lua/vim/treesitter/languagetree.lua#L351) call to [included_regions](https://github.com/neovim/neovim/blob/cd8e15e3373dc9544d582640f043d3dee83a953d/runtime/lua/vim/treesitter/languagetree.lua#L649) is …
> perf(treesitter): set regions early

- lua/trouble/view/treesitter.lua
A recent commit in Neovim (5edbabdbec0) changed the decoration provider API (vim.api.nvim_set_decoration_provider), replacing the on_line callback with on_range.
This breaking change, which also alters the callback arguments, causes an error when using trouble.nvim with recent Neovim nightly builds. This commit updates the call in lua/trouble/view/treesitter.lua to use the new on_range API, restoring compatibility.
- Relevant Neovim Commit: https://github.com/neovim/neovim/commit/5edbabdbec0ac3fba33be8afc008845130158583
- Relevant Neovim PR: https://github.com/neovim/neovim/pull/31400
https://github.com/folke/trouble.nvim/issues/655
> fix(view): adapt to the changes for "nvim_set_decoration_provider"
